# How to use the initial conditions

The initial conditions can be used to start a simulation with a more realistic distribution of the course of the disease in the population.

The argument ``initial_infections`` of the [get_simulate_func](autoapi/sid/index.rst#sid.get_simulate_func) function allows you to indicate individuals who are infected at the start of the simulation. They have randomly drawn courses of the disease, but they all start from the same state, being infected and becoming infectious.

In scenarios where many individuals have already been infected and the disease has spread across the population for a longer time, courses of the diseases are more heterogenous. Thus, you should start a simulation with some kind of "warm-start".

This is what the initial conditions are for. The ``initial_conditions`` argument of [get_simulate_func](autoapi/sid/index.rst#sid.get_simulate_func) is a dictionary of the following form.

```python
initial_conditions = {
    "assort_by": ["region"],
    "burn_in_periods": 14,
    "growth_rate":  1.1,
}
```

In [3]:
import itertools

import numpy as np
import pandas as pd
import sid

In [ ]:
params = sid.get_epidemiological_parameters()

In [2]:
available_ages = [
    "0-9",
    "10-19",
    "20-29",
    "30-39",
    "40-49",
    "50-59",
    "60-69",
    "70-79",
    "80-100",
]

ages = np.random.choice(available_ages, size=10_000)
regions = np.random.choice(["North", "East", "South", "West"], size=10_000)

states = pd.DataFrame({"age_group": ages, "region": regions}).astype("category")
states = sid.simulate._process_initial_states(states, {0: ["region"]})
states = sid.pathogenesis.draw_course_of_disease(states, params, itertools.count(0))

In [4]:
pd.DataFrame(index=pd.RangeIndex(100_000))

Empty DataFrame
Columns: []
Index: [0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30, 31, 32, 33, 34, 35, 36, 37, 38, 39, 40, 41, 42, 43, 44, 45, 46, 47, 48, 49, 50, 51, 52, 53, 54, 55, 56, 57, 58, 59, 60, 61, 62, 63, 64, 65, 66, 67, 68, 69, 70, 71, 72, 73, 74, 75, 76, 77, 78, 79, 80, 81, 82, 83, 84, 85, 86, 87, 88, 89, 90, 91, 92, 93, 94, 95, 96, 97, 98, 99, ...]

[100000 rows x 0 columns]

In [6]:
np.random.choice(10, size=11, replace=False)

ValueError: Cannot take a larger sample than population when 'replace=False'

In [65]:
burn_in_periods = 4
growth_rate = 2

In [75]:
reversed_shares = []
end_of_period_share = 1
for _ in range(burn_in_periods):
    start_of_period_share = end_of_period_share / growth_rate
    added = end_of_period_share - start_of_period_share
    reversed_shares.append(added)
    end_of_period_share = start_of_period_share
shares = np.array(reversed_shares[::-1])

In [76]:
shares / shares.sum()

array([0.06666667, 0.13333333, 0.26666667, 0.53333333])

In [80]:
1 / 15

0.06666666666666667

In [68]:
shares = -np.diff(1 / growth_rate ** np.arange(burn_in_periods + 1))[::-1]

In [81]:
shares[-1] = 1 - np.sum([shares[:-1]])

In [82]:
shares

array([0.0625, 0.125 , 0.25  , 0.5625])

In [33]:
multiplier = 1.3

In [34]:
np.exp(np.log(1.3) / 10)

1.026583631304232

In [50]:
x = (1.026583631304232 ** np.arange(1, 11)) - 1

In [51]:
x / x.sum()

array([0.01677053, 0.03398687, 0.05166089, 0.06980476, 0.08843095,
       0.10755229, 0.12718194, 0.14733343, 0.16802061, 0.18925774])

- Remove growth factor
- Decide whether all things should be in params or the dictionary